// Compiling SCSS to CSS

module.exports =
{
    dist:
    {
        options:
        {
            sassDir: 'src',
            cssDir: 'dist',
            noLineComments: true    // Disable the comment traces generated by compass
        }
    }
};
